/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.firstproject.cliente.infrastructure.in;

/**
 *
 * @author camper
 */
public class CreateUserForm extends javax.swing.JPanel {

    /**
     * Creates new form CreateUserForm
     */
    public CreateUserForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createUserForm = new javax.swing.JPanel();
        primerNombreField = new javax.swing.JTextField();
        segundoNombreField = new javax.swing.JTextField();
        primerNombreLabel = new javax.swing.JLabel();
        segundoNombreLabel = new javax.swing.JLabel();
        primerApellidoLabel = new javax.swing.JLabel();
        primerApellidoField = new javax.swing.JTextField();
        primerApellidoField1 = new javax.swing.JTextField();
        segundoApellidoLabel = new javax.swing.JLabel();

        createUserForm.setBackground(new java.awt.Color(51, 51, 51));

        primerNombreField.setBackground(new java.awt.Color(204, 204, 204));
        primerNombreField.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        primerNombreField.setForeground(new java.awt.Color(51, 51, 51));
        primerNombreField.setText("jTextField1");

        segundoNombreField.setBackground(new java.awt.Color(204, 204, 204));
        segundoNombreField.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        segundoNombreField.setForeground(new java.awt.Color(51, 51, 51));
        segundoNombreField.setText("jTextField1");
        segundoNombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoNombreFieldActionPerformed(evt);
            }
        });

        primerNombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        primerNombreLabel.setLabelFor(primerNombreField);
        primerNombreLabel.setText("primer nombre:");

        segundoNombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        segundoNombreLabel.setLabelFor(segundoNombreField);
        segundoNombreLabel.setText("segundo nombre:");

        primerApellidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        primerApellidoLabel.setLabelFor(primerApellidoField);
        primerApellidoLabel.setText("primer apellido:");

        primerApellidoField.setBackground(new java.awt.Color(204, 204, 204));
        primerApellidoField.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        primerApellidoField.setForeground(new java.awt.Color(51, 51, 51));
        primerApellidoField.setText("jTextField1");

        primerApellidoField1.setBackground(new java.awt.Color(204, 204, 204));
        primerApellidoField1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        primerApellidoField1.setForeground(new java.awt.Color(51, 51, 51));
        primerApellidoField1.setText("jTextField1");

        segundoApellidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        segundoApellidoLabel.setLabelFor(primerApellidoField);
        segundoApellidoLabel.setText("segundo apellido:");

        javax.swing.GroupLayout createUserFormLayout = new javax.swing.GroupLayout(createUserForm);
        createUserForm.setLayout(createUserFormLayout);
        createUserFormLayout.setHorizontalGroup(
            createUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserFormLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(createUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primerNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primerNombreLabel)
                    .addComponent(primerApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primerApellidoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(createUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(segundoNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundoNombreLabel)
                    .addComponent(primerApellidoField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundoApellidoLabel))
                .addGap(14, 14, 14))
        );
        createUserFormLayout.setVerticalGroup(
            createUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserFormLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(createUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primerNombreLabel)
                    .addComponent(segundoNombreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primerNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundoNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createUserFormLayout.createSequentialGroup()
                        .addComponent(primerApellidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(primerApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createUserFormLayout.createSequentialGroup()
                        .addComponent(segundoApellidoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(primerApellidoField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(351, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createUserForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createUserForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void segundoNombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoNombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segundoNombreFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel createUserForm;
    private javax.swing.JTextField primerApellidoField;
    private javax.swing.JTextField primerApellidoField1;
    private javax.swing.JLabel primerApellidoLabel;
    private javax.swing.JTextField primerNombreField;
    private javax.swing.JLabel primerNombreLabel;
    private javax.swing.JLabel segundoApellidoLabel;
    private javax.swing.JTextField segundoNombreField;
    private javax.swing.JLabel segundoNombreLabel;
    // End of variables declaration//GEN-END:variables
}
