version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-farmacia
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: farmacia
    ports:
      - "3306:3306"
    volumes:
      - ./database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./database/dml.sql:/docker-entrypoint-initdb.d/dml.sql
